[package]
name = "mss-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "1.0.2"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
clap = "4.1.4"
once_cell = "1.17.0"
axum = "0.6.6"
itertools = "0.10.5"
ethers-providers = "1.0.2"
serde_json = "1.0.93"
eyre = "0.6.8"
